### ISSUE TITLE
[REFACT] Global Execption 및  Error Code 수정 

### ISSUE THREAD

**Issue by khwoowoo** [woorifisa-projects-3rd/WeKids-BE#51]
# ⚙️ ISSUE
- 11월 24일 멘토링 피드백 반영

# 📄 To-Do
- [x] 다양한 에러에도 응답 줄 수 있도록 수정
- [x] 데이터를 잘 못 전달 받았을 때 Bad Request가 아니라 500으로 나올 수 있도록 수정
- [x] 에러 응답에서 http status code 삭제하고 http header에서 판단할 수 있도록 밴경
