### ISSUE TITLE
[CI] 운영 인프라 CI/CD 파이프라인 구축

### ISSUE THREAD

**Issue by khwoowoo** [woorifisa-projects-3rd/WeKids-BE#72]
# ⚙️ ISSUE
- 운영 인프라 CI/CD 파이프라인 구축
- CodeDepoly, S3, Auto Scaling Group으로 구축

# 📄 To-Do
- [x] IAM 권한 생성
- [x] CodeDepoly Agent, Docker, Docker-compose 설치 및 AMI
- [x] ELB, Target Group 설정
- [x] CodeDepoly 설치
- [x] CI 설정
